version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    env_file: .env
    depends_on:
      - postgres
      - redis
    command: 
      - python manage.py migrate
      - daphne -b 0.0.0.0 -p 8000 config.asgi:application # only use daphne to serve both ws and http
    expose:
      - 8000

  # worker:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/django/Dockerfile
  #   command: python manage.py runworker
  #   env_file: .env
  #   depends_on:
  #     - postgres
  #     - redis

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      
  # caddy:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/caddy/Dockerfile
  #   depends_on:
  #     - django
  #   volumes:
  #     - caddy:/root/.caddy
  #   env_file: .env
  #   ports:
  #     - "0.0.0.0:80:80"
  #     - "0.0.0.0:443:443"

  redis:
    image: redis:4.0
